import { useEffect, useState } from 'react';
import type { AnalyticsDataStatus } from '@genius-support-os/contracts';
import { getCeoHistory, getCeoSnapshot } from './analytics-api';
import type { AnalyticsFilters, AnalyticsPageProps, CeoHistory, CeoSnapshot } from './analytics-model';
import { DEFAULT_ANALYTICS_FILTERS } from './analytics-model';
import { AnalyticsFilters as Filters } from './AnalyticsFilters';
import { AnalyticsLoadingState, AnalyticsRetryAction, AnalyticsStateBadge, KpiCard, formatCountLabel } from './analytics-ui';
import { resolveAnalyticsPeriod } from './analytics-periods';
import { buildExecutiveExceptions, rankExecutivePipelines } from './analytics-executive';

const STATUS_LABELS: Record<AnalyticsDataStatus, string> = {
  fresh: 'Atualizado', stale: 'Pode estar atrasado', partial: 'Dados parciais', empty: 'Sem registros no recorte', not_configured: 'Fonte não configurada', syncing: 'Sincronizando', unavailable: 'Fonte indisponível', error: 'Erro na fonte',
};

export function AnalyticsCeoPage({ sharedPeriod, onSharedPeriodChange, onRetry, isDashboardViewer = false }: AnalyticsPageProps) {
  const period = sharedPeriod ?? resolveAnalyticsPeriod('month');
  const [filters, setFilters] = useState<AnalyticsFilters>({ ...DEFAULT_ANALYTICS_FILTERS, ...period });
  const [result, setResult] = useState<{ loading: boolean; data?: CeoSnapshot; history?: CeoHistory; error?: boolean }>({ loading: true });
  const [refreshing, setRefreshing] = useState(false);
  const [domainScope, setDomainScope] = useState<'all' | 'commercial' | 'cs' | 'finance'>('all');

  useEffect(() => setFilters((current) => ({ ...current, ...period })), [period.from, period.to]);
  useEffect(() => {
    let cancelled = false;
    setRefreshing(true);
    setResult((current) => current.data ? { ...current, loading: false, error: undefined } : { loading: true });
    Promise.all([getCeoSnapshot(filters), getCeoHistory(filters)]).then(([data, history]) => { if (!cancelled) { setResult({ loading: false, data, history }); setRefreshing(false); } }).catch(() => { if (!cancelled) { setResult((current) => ({ ...current, loading: false, error: true })); setRefreshing(false); } });
    return () => { cancelled = true; };
  }, [filters]);

  if (result.loading && !result.data) return <AnalyticsLoadingState title="Conjurando seus dados" description="Estamos preparando sua visão executiva." />;
  if (result.error || !result.data) return <StatePanel title="Não foi possível carregar a visão executiva" description="Os indicadores estão indisponíveis no momento. Tente novamente." onRetry={onRetry} />;

  const data = result.data;
  const state = data.state;
  const exceptions = buildExecutiveExceptions(data);
  const pipelines = rankExecutivePipelines(data.support.byPipeline);
  const currentPosition = [
    { label: 'Saldo vencido', value: data.finance.overdueBalance > 0 ? formatCurrency(data.finance.overdueBalance) : data.finance.overdueTitles === 0 ? 'R$ 0' : 'Indisponível', hint: formatCountLabel(data.finance.overdueTitles, 'título vencido', 'títulos vencidos'), tone: data.finance.overdueBalance > 0 ? 'critical' as const : 'neutral' as const },
    { label: 'Clientes com alerta', value: data.financialAlerts.length.toLocaleString('pt-BR'), hint: 'Inadimplência reconciliada', tone: data.financialAlerts.length > 0 ? 'warning' as const : 'neutral' as const },
    { label: 'Carteira de suporte', value: data.support.openTickets.toLocaleString('pt-BR'), hint: formatCountLabel(data.support.highPriorityOpen, 'alta prioridade aberta', 'altas prioridades abertas'), tone: data.support.highPriorityOpen > 0 ? 'warning' as const : 'neutral' as const },
  ];
  const domainCards = [
    { title: 'Comercial', description: 'Como o período evoluiu', value: formatCurrency(data.commercial.wonRevenue), details: `${formatCountLabel(data.commercial.openDeals, 'negócio aberto', 'negócios abertos')} · ${formatCountLabel(data.commercial.wonDeals, 'ganho', 'ganhos')}`, href: '/admin/analytics/commercial' },
    { title: 'CS / Suporte', description: 'Onde a operação pede atenção', value: formatCountLabel(data.support.openTickets, 'ticket aberto', 'tickets abertos'), details: `${formatCountLabel(data.support.highPriorityOpen, 'alta prioridade', 'altas prioridades')} · ${formatPercent(data.support.closedRate)} encerrados`, href: '/admin/analytics/cs' },
    { title: 'Financeiro', description: 'Qual é a posição financeira', value: formatCurrency(data.finance.balance), details: `${formatCountLabel(data.finance.unmatchedTitles, 'título sem correspondência', 'títulos sem correspondência')}`, href: '/admin/analytics/finance' },
  ];
  return <div className="space-y-5" data-testid="executive-dashboard">
    <section className="flex flex-col gap-3 rounded-xl border border-[color:var(--minimal-border)] bg-[color:var(--minimal-surface-muted)] px-4 py-4 lg:flex-row lg:items-center lg:justify-between" aria-labelledby="executive-heading">
      <div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[color:var(--minimal-text-secondary)]">Visão executiva</p><h2 id="executive-heading" className="mt-1 text-xl font-semibold tracking-[-0.02em] text-[color:var(--minimal-text)]">Decida com o contexto certo</h2><p className="mt-1 text-sm text-[color:var(--minimal-text-secondary)]">Desempenho do período, posição atual e prioridades operacionais em um só lugar.</p></div>
      <div className="flex flex-col items-start gap-1 lg:items-end"><span className="text-xs text-[color:var(--minimal-text-secondary)]">Consolidação {state ? STATUS_LABELS[state.status].toLocaleLowerCase('pt-BR') : 'não registrada'}</span><AnalyticsStateBadge state={state} /></div>
    </section>
    <div className="flex flex-col gap-3 lg:flex-row lg:items-end"><div className="min-w-44"><label className="flex flex-col gap-1.5 text-xs font-medium text-[color:var(--minimal-text-secondary)]" htmlFor="executive-domain">Domínio em foco<select id="executive-domain" value={domainScope} onChange={(event) => setDomainScope(event.target.value as typeof domainScope)} className="h-9 rounded-md border border-[color:var(--minimal-border)] bg-[color:var(--minimal-surface)] px-2.5 text-sm font-normal text-[color:var(--minimal-text)]"><option value="all">Todos os domínios</option><option value="commercial">Comercial</option><option value="cs">CS / Suporte</option><option value="finance">Financeiro</option></select></label></div><div className="min-w-0 flex-1"><Filters value={filters} onApply={(next) => { setFilters(next); onSharedPeriodChange?.({ from: next.from, to: next.to }); }} stageOptions={[]} /></div></div>
    {refreshing ? <p className="text-xs text-[color:var(--minimal-text-secondary)]" role="status">Atualizando o período selecionado...</p> : null}
    {state?.status === 'empty' ? <p className="rounded-lg border border-dashed border-[color:var(--minimal-border-strong)] px-3 py-2 text-sm text-[color:var(--minimal-text-secondary)]" role="status">Nenhum registro no período selecionado. A posição atual continua disponível quando a fonte correspondente respondeu.</p> : null}
    <section aria-labelledby="performance-heading"><SectionHeading id="performance-heading" title="Desempenho no período" description="Indicadores afetados pelo recorte selecionado." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Receita ganha" value={formatCurrency(data.commercial.wonRevenue)} hint={formatCountLabel(data.commercial.wonDeals, 'ganho', 'ganhos')} temporalType="Período selecionado" state={state?.status === 'fresh' ? undefined : state} /><KpiCard label="Negócios ganhos" value={data.commercial.wonDeals.toLocaleString('pt-BR')} hint={formatCountLabel(data.commercial.lostDeals, 'perdido', 'perdidos')} temporalType="Período selecionado" state={state?.status === 'fresh' ? undefined : state} /><KpiCard label="Conversão" value={formatPercent(data.commercial.conversionRate)} hint="Ganhos sobre ganhos e perdas" temporalType="Período selecionado" state={state?.status === 'fresh' ? undefined : state} /><KpiCard label="Tickets criados" value={data.support.createdTickets.toLocaleString('pt-BR')} hint={formatCountLabel(data.support.closedTickets, 'encerrado', 'encerrados')} temporalType="Período selecionado" state={data.support.highPriorityOpen > 0 ? { ...(state ?? { status: 'fresh', source: 'HubSpot / Tickets', asOf: null, lastSuccessfulSyncAt: null, syncRunId: null, coverage: { expected: null, received: null }, reason: null }), status: 'partial' } : undefined} /></div></section>
    <section aria-labelledby="current-heading"><SectionHeading id="current-heading" title="Posição atual" description="Posição atual, não afetada pelo período selecionado." /><div className="grid gap-3 md:grid-cols-3">{currentPosition.map((item) => <KpiCard key={item.label} {...item} />)}</div></section>
    {exceptions.length > 0 ? <section aria-labelledby="exceptions-heading"><SectionHeading id="exceptions-heading" title="Exceções que exigem atenção" description="Regras determinísticas priorizadas por gravidade e impacto." /><div className="grid gap-3 lg:grid-cols-3">{exceptions.map((item) => <a key={item.key} href={item.href} className={`rounded-xl border p-4 transition hover:border-[color:var(--minimal-border-strong)] ${item.severity === 3 ? 'border-[color:var(--minimal-danger-border)] bg-[color:var(--minimal-danger-surface)]' : 'border-[color:var(--minimal-warning-border)] bg-[color:var(--minimal-warning-surface)]'}`}><span className="text-xs font-semibold uppercase tracking-wide text-[color:var(--minimal-text-secondary)]">{item.domain}</span><h3 className="mt-2 text-sm font-semibold text-[color:var(--minimal-text)]">{item.title}</h3><p className="mt-1 text-sm text-[color:var(--minimal-text-secondary)]">{item.detail}</p><span className="mt-3 inline-block text-xs font-semibold text-[color:var(--minimal-action)]">{item.action} →</span></a>)}</div></section> : <section className="rounded-xl border border-[color:var(--minimal-border)] bg-[color:var(--minimal-surface-muted)] px-4 py-3" role="status"><p className="text-sm font-medium text-[color:var(--minimal-text)]">Nenhuma exceção determinística no recorte.</p></section>}
    <section aria-labelledby="domains-heading"><SectionHeading id="domains-heading" title="Resumo por domínio" description={isDashboardViewer ? 'Resumo informativo das áreas operacionais.' : 'Aprofunde somente quando a leitura executiva indicar necessidade.'} /><div className="grid gap-3 lg:grid-cols-3">{domainCards.filter((card) => domainScope === 'all' || (domainScope === 'commercial' && card.title === 'Comercial') || (domainScope === 'cs' && card.title === 'CS / Suporte') || (domainScope === 'finance' && card.title === 'Financeiro')).map((card) => <div key={card.title} className="rounded-xl border border-[color:var(--minimal-border)] bg-[color:var(--minimal-surface)] p-4"><h3 className="text-sm font-semibold text-[color:var(--minimal-text)]">{card.title}</h3><p className="mt-1 text-xs text-[color:var(--minimal-text-secondary)]">{card.description}</p><p className="mt-4 text-xl font-semibold tabular-nums text-[color:var(--minimal-text)]">{card.value}</p><p className="mt-1 text-xs text-[color:var(--minimal-text-secondary)]">{card.details}</p>{isDashboardViewer ? <span className="mt-4 inline-block text-xs text-[color:var(--minimal-text-tertiary)]">Aprofundamento restrito ao perfil</span> : <a href={card.href} className="mt-4 inline-block text-xs font-semibold text-[color:var(--minimal-action)]">Abrir domínio →</a>}</div>)}</div></section>
    <section aria-labelledby="pipelines-heading"><SectionHeading id="pipelines-heading" title="Pipelines prioritários" description="Ranking determinístico por volume de tickets ativos no recorte." />{pipelines.length ? <div className="overflow-hidden rounded-xl border border-[color:var(--minimal-border)]"><ul className="divide-y divide-[color:var(--minimal-border)]">{pipelines.map((pipeline) => <li key={pipeline.id}><a href={pipeline.href} className="flex items-center justify-between gap-3 px-4 py-3 transition hover:bg-[color:var(--minimal-surface-muted)]"><span className="min-w-0"><span className="block truncate text-sm font-medium text-[color:var(--minimal-text)]">{pipeline.label}</span><span className="text-xs text-[color:var(--minimal-text-secondary)]">{pipeline.domain}</span></span><span className="shrink-0 text-sm font-semibold tabular-nums text-[color:var(--minimal-text)]">{formatCountLabel(pipeline.count, 'ticket', 'tickets')} <span aria-hidden="true">→</span></span></a></li>)}</ul></div> : <div className="rounded-xl border border-dashed border-[color:var(--minimal-border-strong)] px-4 py-5 text-sm text-[color:var(--minimal-text-secondary)]">Nenhum pipeline com atividade no período selecionado.</div>}</section>
    {result.history ? <p className="text-xs text-[color:var(--minimal-text-tertiary)]">Comparação temporal disponível para o mesmo recorte: {formatCurrency(result.history.current.commercial.wonRevenue)} no período atual.</p> : null}
  </div>;
}

function SectionHeading({ id, title, description }: { id: string; title: string; description: string }) { return <div className="mb-3"><h2 id={id} className="text-sm font-semibold text-[color:var(--minimal-text)]">{title}</h2><p className="mt-1 text-xs text-[color:var(--minimal-text-secondary)]">{description}</p></div>; }
function StatePanel({ title, description, onRetry }: { title: string; description: string; onRetry?: () => void }) { return <section className="rounded-xl border border-[color:var(--minimal-border)] bg-[color:var(--minimal-surface-muted)] px-5 py-8 text-center" role="alert"><h2 className="text-base font-semibold text-[color:var(--minimal-text)]">{title}</h2><p className="mt-1 text-sm text-[color:var(--minimal-text-secondary)]">{description}</p><div className="mt-4 flex justify-center"><AnalyticsRetryAction onRetry={onRetry} /></div></section>; }
function formatCurrency(value: number) { return value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }); }
function formatPercent(value: number) { return `${(value * 100).toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%`; }
